apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/log/nginx
            name: nginx-logs
          - mountPath: /var/www/symfony
            name: symfony
          - mountPath: /var/www/symfony/var/logs
            name: symfony-logs
      volumes:
      - name: nginx-logs
        persistentVolumeClaim:
          claimName: nginx-logs
      - name: symfony
        persistentVolumeClaim:
          claimName: symfony
      - name: symfony-logs
        persistentVolumeClaim:
          claimName: symfony-logs
status: {}
