apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: symfony
    spec: 
      containers: 
      - name: jenkins
        image: jenkins/jenkins:lts
        ports: 
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JENKINS_OPTS
          valueFrom:
            secretKeyRef:
              name: secrets
              key: jenkins_options
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
      volumes:
      - name: jenkins-home
        emptyDir: {}
