kind: PersistentVolume
apiVersion: v1
metadata:
  name: www-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: www-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
