#apiVersion: apps/v1beta1
#kind: Deployment
#metadata:
#  name: nginx
#  labels:
#    app: nginx
#spec:
#  replicas: 5
#  strategy:
#    type: Recreate
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      restartPolicy: Always
#      volumes:
#      - name: www-storage
#        persistentVolumeClaim:
#          claimName: nginx-claim
#      containers:
#      - name: nginx
#        image: nginx
#        ports:
#        - containerPort: 80
#          name: "http-server"
#        volumeMounts:
#        - mountPath: "/usr/share/nginx/html"
#          name: www-storage

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  volumes:
    - name: www-storage
      persistentVolumeClaim:
        claimName: www-claim
  containers:
    - name: www-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: www-storage

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
