apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: symfony
spec:
  selector:
    app: symfony
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: symfony
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: symfony
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/log/nginx
            name: nginx-logs-claim
          - mountPath: /var/www/symfony
            name: symfony-claim
          - mountPath: /var/www/symfony/var/logs
            name: symfony-logs-claim
      volumes:
      - name: nginx-logs-claim
        persistentVolumeClaim:
          claimName: nginx-logs-claim
      - name: symfony-claim
        persistentVolumeClaim:
          claimName: symfony-claim
      - name: symfony-logs-claim
        persistentVolumeClaim:
          claimName: symfony-logs-claim
status: {}
