apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-webroot
  labels:
    app: symfony
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: symfony
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: nginx
        image: carlosas/nginx-symfony
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/application
          name: workdir   
      - name: php
        image: carlosas/phpfpm-symfony
        volumeMounts:
         - mountPath: /var/www/application
           name: workdir        
      volumes:
      - name: workdir
#        emptyDir: {}
        persistentVolumeClaim:
          claimName: pvc-webroot
