apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-webroot
  labels:
    type: local
#  annotations:
#    pv.beta.kubernetes.io/gid: "webfiles"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
